version: '3.8'

services:
  mysql:
    container_name: mysql-obn
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: open_books
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-obn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  obn-api:
    container_name: obn-api
    image: obn/obn:1.0.0
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - mysql

#  keycloak:
#    container_name: keycloak-obn
#    image: quay.io/keycloak/keycloak:24.0.2
#    ports:
#      - 9090:8080
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    networks:
#      - spring-demo
#    command:
#      - "start-dev"

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  keycloak:
    driver: local
