spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
springdoc:
  default-produces-media-type: application/json
server:
  servlet:
    context-path: /api/v1
